version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      # Install Poetry
      - run:
          name: Install Poetry
          command: |
            curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
            export PATH="$HOME/.poetry/bin:$PATH"

      # Install project dependencies
      - run:
          name: Install dependencies
          command: |
            poetry install

      # Run unit tests
      - run:
          name: Run unit tests
          command: |
            poetry run pytest

      # Log in to Docker Hub
      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/casetext:latest .

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/casetext:latest

workflows:
  build-and-push:
    jobs:
      - build:
          name: build-step
          context:
            - services