version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: 
      name: python/default
      tag: '3.12' 
      
    steps:
      - checkout

      - python/install-packages:
          pkg-manager: poetry

      - run:
          name: Install dependencies
          command: |
            poetry install

      - run:
          name: Run unit tests
          command: |
            poetry run pytest

      - run:
          name: Log in to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKER_USERNAME/casetext:latest .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker push $DOCKER_USERNAME/casetext:latest

workflows:
  build-and-push:
    jobs:
      - build:
          name: build-step